/**
  ******************************************************************************
  * @file    Libraries/Device/Phoenix/source/tx_phe_itm.c
  * @author  HUGE-IC Application Team
  * @version V1.0.0
  * @date    01-08-2018
  * @brief   CMSIS Cortex-M3 Device Peripheral Access Layer System Source File.
  *          This file contains the system clock configuration for Phoenix devices,
  *          and is generated by the clock configuration tool.
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; COPYRIGHT 2018 HUGE-IC</center></h2>
  *
  *
  *
  ******************************************************************************
  */ 

#if DEBUG_ITM
/* Includes ------------------------------------------------------------------*/
#include "stdio.h"
#include "tx_phe.h"

/** @addtogroup StdPeriph_Driver
  * @{
  */
  
/** @defgroup ITM 
  * @brief ITM driver modules
  * @{
  */
 
/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
#pragma import(__use_no_semihosting_swi)

//struct __FILE { int handle; /* Add whatever you need here */ };
//FILE __stdout;
//FILE __stdin;
//volatile int32_t ITM_RxBuffer;

/* Private function prototypes -----------------------------------------------*/
/* Private functions ---------------------------------------------------------*/
  

/** @defgroup ITM_Group ITM Read and Write
 *  @brief   ITM Read and Write
 *
@verbatim   
 ===============================================================================
                              ITM Read and Write
 ===============================================================================  

@endverbatim
  * @{
  */

/**
  * @brief  ferror
  * @param  f: Printed entry pointer
  * @retval Return result
  */
int ferror(FILE *f) 
{
    /* Your implementation of ferror */
    return EOF;
}

/**
  * @brief  _ttywrch
  * @param  ch: The value of the string to print
  * @retval None
  */
void _ttywrch(int ch) 
{
    int file = 0;
    fputc(ch, (FILE *)file);
}

/**
  * @brief  _sys_exit
  * @param  return_code: Return wrong information
  * @retval None
  */
void _sys_exit(int return_code) 
{
    while (1);    /* endless loop */
}

/**
  * @}
  */ 

/**
  * @}
  */

/**
  * @}
  */ 
#endif

/*************************** (C) COPYRIGHT 2018 HUGE-IC ***** END OF FILE *****/
